
[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[general]
import = ["/home/ivan/.config/alacritty/themes/wallpaper.toml"]

[window]
padding = { x = 12, y = 12 }
opacity = 0.95
blur = true
